name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.SurvivalHavenPlugin
author: FreshLlamanade
api-version: 1.19

permissions:
  survivalhaven.admin:
    description: Allows a player full access to the plugin
    default: op
