name: SurvivalHavenPlugin
main: me.monst.survivalhaven.SurvivalHavenPlugin
version: 1.0.2
api-version: 1.13
softdepend:
  - Essentials

permissions:
  survivalhaven.guide:
    description: Allows a player access to the /guide command, including /guide coords, /guide here, and /guide stop
    default: op
  survivalhaven.guide.death:
    description: Allows a player additional access to the /guide death command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.guide.player:
    description: Allows a player additional access to the /guide player command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.guide.home:
    description: Allows a player additional access to the /guide home command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.breadcrumbs.*:
    description: Allows a player unlimited length access to the /breadcrumbs command
    default: op
  survivalhaven.admin:
    description: Allows a player to manage the plugin
    default: op
