name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.SurvivalHavenPlugin
author: FreshLlamanade
api-version: 1.19
softdepend:
  - Essentials

permissions:
  survivalhaven.guide:
    description: Allows a player access to the /guide command, including /guide coords, /guide here, and /guide stop
    default: op
  survivalhaven.guide.death:
    description: Allows a player additional access to the /guide death command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.guide.player:
    description: Allows a player additional access to the /guide player command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.guide.home:
    description: Allows a player additional access to the /guide home command
    default: op
    children:
      survivalhaven.guide: true
  survivalhaven.guide.*:
    description: Allows a player full access to the /guide command
    default: op
    children:
      survivalhaven.guide: true
      survivalhaven.guide.death: true
      survivalhaven.guide.player: true
      survivalhaven.guide.home: true
  survivalhaven.breadcrumbs.*:
    description: Allows a player unlimited length access to the /breadcrumbs command
    default: op
  survivalhaven.admin:
    description: Allows a player to manage the plugin
    default: op
  survivalhaven.*:
    description: Allows a player full access to the plugin
    default: op
    children:
      survivalhaven.guide.*: true
      survivalhaven.breadcrumbs.*: true
      survivalhaven.admin: true
